name: Frontend Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Backend-Build-And-Deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy React app to GitHub Pages
      with:
        working-directory: ./frontend
      uses: omkartapale/react-deployment-gh-pages@v1.0.0