name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Building React app
        working-directory: ./backend
        run: |
            npm run build
            ls
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: hiransanjeewa/student-management-system-backend:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_INSTANCE_IP }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
          sudo apt update
          sudo apt install -y docker.io

          docker stop student-management-system-backend
          docker rm student-management-system-backend
         
        
          docker rmi hiransanjeewa/student-management-system-backend:latest
         

          docker image prune
          docker container prune
         
          docker pull hiransanjeewa/student-management-system-backend:latest
   
          docker run -d -p 80:5000 --name hiransanjeewa/student-management-system-backend:latest
           
          docker ps
          docker images
          docker ps -a
          
